# Generated by Django 5.1.1 on 2024-10-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.TextField(),
        ),
    ]
