# Generated by Django 5.1.1 on 2024-10-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tony', '0002_alter_blog_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
